### ISSUE TITLE
Using the network visualisation tool crashes the client (and server?)

### ISSUE THREAD

**Issue by jpeaglesandkatz** [bdew/ae2stuff#120]
Using the network visualisation tool crashes the client (and server?)

Not only that, after using it once it crashes your client/world and after that are unable to load your world again.

1.10.2 running AE2-r4-aplha 6

and ae2stuff-0.6.0.5-mc1.10.2

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (sampler-1.66.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-6.jar)
  DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  IC2core (industrialcraft-2-2.6.87-ex110.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  LoadingPlugin (Quark-r1.0-55.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 11/16/16 12:29 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at appeng.parts.CableBusStorage.getSide(CableBusStorage.java:52)
	at appeng.parts.CableBusContainer.getPart(CableBusContainer.java:326)
	at appeng.parts.CableBusContainer.getGridNode(CableBusContainer.java:676)
	at appeng.tile.networking.TileCableBus.getGridNode(TileCableBus.java:153)
	at net.bdew.ae2stuff.items.visualiser.ItemVisualiser$$anonfun$onUpdate$2$$anonfun$apply$1.apply(ItemVisualiser.scala:85)
	at net.bdew.ae2stuff.items.visualiser.ItemVisualiser$$anonfun$onUpdate$2$$anonfun$apply$1.apply(ItemVisualiser.scala:84)
	at scala.Option.foreach(Option.scala:245)
	at net.bdew.ae2stuff.items.visualiser.ItemVisualiser$$anonfun$onUpdate$2.apply(ItemVisualiser.scala:84)
	at net.bdew.ae2stuff.items.visualiser.ItemVisualiser$$anonfun$onUpdate$2.apply(ItemVisualiser.scala:83)
	at scala.Option$WithFilter.foreach(Option.scala:208)
	at net.bdew.ae2stuff.items.visualiser.ItemVisualiser$.func_77663_a(ItemVisualiser.scala:83)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:441)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:344)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:510)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

**Comment by b0bst3r** [comment]
Confirmed, had to edit out the visualiser from the players inventory so he could log in again.

**Comment by jpeaglesandkatz** [comment]
I would hate to see that this mod is dropped. It offers such amazing enhancements over standard AE2.

The advanced inscriber is bugged (need only 1 inscriber press but doesn't seem to handle that very well).

Sorry for the side comment but wasn't sure to open a ticket about that one.

**Comment by bdew** [comment]
> I would hate to see that this mod is dropped. It offers such amazing enhancements over standard AE2.

Dropped from where? This is alpha, shit might be bugged.

> The advanced inscriber is bugged (need only 1 inscriber press but doesn't seem to handle that very well).

Please open a proper bug report with a proper description of the problem

> Sorry for the side comment but wasn't sure to open a ticket about that one.

If you don't report bugs they won't get fixed...

**Comment by bdew** [comment]
Crash should be fixed with next build i hope, please test: https://minecraft.curseforge.com/projects/ae2-stuff/files/2346048

**Comment by jpeaglesandkatz** [comment]
No more crash with this version. Thanks!
