### ISSUE TITLE
Server Crash - NoSuchMethodError: appeng.api.features.IInscriberRegistry.getRecipes

### ISSUE THREAD

**Issue by ProsperCraft** [bdew/ae2stuff#139]
https://gist.github.com/ProsperCraft/55387f5af178c69469f7533d61994fc4

Description: Ticking block entity

java.lang.NoSuchMethodError: appeng.api.features.IInscriberRegistry.getRecipes()Ljava/util/List;
	at net.bdew.ae2stuff.machines.inscriber.TileInscriber.findFinalRecipe(TileInscriber.scala:128)
	at net.bdew.ae2stuff.machines.inscriber.TileInscriber$$anonfun$1.apply$mcV$sp(TileInscriber.scala:59)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at net.bdew.lib.Event0.trigger(Event.scala:19)
	at net.bdew.lib.tile.TileExtended.func_145845_h(TileExtended.scala:63)
	at net.minecraft.world.World.func_72939_s(World.java:2583)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ProsperCraft** [comment]
Server was in a crashloop, here is another one.
https://gist.github.com/ProsperCraft/9de94dd13a1fa8b3d9ad156e872b35de

java.lang.NoClassDefFoundError: appeng/core/WorldSettings
	at net.bdew.ae2stuff.grid.GridTile$$anonfun$1.apply$mcV$sp(GridTile.scala:37)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at net.bdew.lib.Event0.trigger(Event.scala:19)
	at net.bdew.lib.tile.TileExtended.func_145845_h(TileExtended.scala:63)
	at net.minecraft.world.World.func_72939_s(World.java:2583)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: appeng.core.WorldSettings
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
Caused by: java.lang.NullPointerException

**Comment by bdew** [comment]
Use rv3 version of AE2 Stuff if you are using AE2 rv3 ....

https://minecraft.curseforge.com/projects/ae2-stuff/files/2270295

**Comment by Janzinho30** [comment]
i am using the last version of ae2 stuff and still crashing
