### ISSUE TITLE
been getting this error 

### ISSUE THREAD

**Issue by abdullamu** [bdew/ae2stuff#14]
hello 
i get this error in console after updating ae2 but no crash when load ae2 grystal growth so when i load overworld

[23:27:51] [pool-7-thread-1/ERROR]: A TileEntity ae2stuff.Grower(net.bdew.ae2stuff.machines.grower.TileGrower) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.RuntimeException: Grid Features are Server Side Only.
	at appeng.core.Api.createGridNode(Api.java:108) ~[Api.class:?]
	at net.bdew.ae2stuff.grid.GridTile$$anonfun$3.apply(GridTile.scala:48) ~[GridTile$$anonfun$3.class:?]
	at net.bdew.ae2stuff.grid.GridTile$$anonfun$3.apply(GridTile.scala:45) ~[GridTile$$anonfun$3.class:?]
	at net.bdew.lib.Event1$$anonfun$trigger$2.apply(Event.scala:23) ~[Event1$$anonfun$trigger$2.class:?]
	at net.bdew.lib.Event1$$anonfun$trigger$2.apply(Event.scala:23) ~[Event1$$anonfun$trigger$2.class:?]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[List.class:?]
	at net.bdew.lib.Event1.trigger(Event.scala:23) ~[Event1.class:?]
	at net.bdew.lib.tile.TileExtended.func_145839_a(TileExtended.scala:39) ~[TileExtended.class:?]
	at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:116) [aor.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:496) [aqk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75815_a(AnvilChunkLoader.java:82) [aqk.class:?]
	at com.thevoxelbox.voxelmap.b.c.b(Unknown Source) [c.class:?]
	at com.thevoxelbox.voxelmap.b.e.a(Unknown Source) [e.class:?]
	at com.thevoxelbox.voxelmap.b.a.run(Unknown Source) [a.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_31]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_31]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]

**Comment by bdew** [comment]
Voxelmap is doing something really really weird. I'll see if i can add a workaround for that.

**Comment by bdew** [comment]
Please try this build: http://jenkins.bdew.net/job/ae2stuff-1.7.10/16/artifact/build/libs/ae2stuff-mc1710-0.1.7.16.jar

**Comment by abdullamu** [comment]
its fixed thank you kindly
