### ISSUE TITLE
[1.12] Crystal Growth Chamber crashes the game

### ISSUE THREAD

**Issue by 0blu** [bdew/ae2stuff#157]
When I placed the Crystal Growth Chamber the game crashed. (Crashes also occur when using other ae2stuff blocks)
It seems that the version of ae2stuff is incompatible with my ae2 version.

`appliedenergistics2-rv5-alpha-7`
`ae2stuff-0.7.0.3-mc1.12.2`

If so, what version do I have to use and _why is no error occurring when ae2stuff loads_?

```
java.lang.NoSuchMethodError: appeng.api.IAppEngApi.grid()Lappeng/api/networking/IGridHelper;
	at net.bdew.ae2stuff.grid.GridTile$class.getNode(GridTile.scala:79)
	at net.bdew.ae2stuff.machines.grower.TileGrower.getNode(TileGrower.scala:30)
	at net.bdew.ae2stuff.grid.GridTile$$anonfun$1.apply$mcV$sp(GridTile.scala:37)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at net.bdew.lib.Event0.trigger(Event.scala:19)
	at net.bdew.lib.tile.TileTicking$class.update(TileTicking.scala:24)
	at net.bdew.ae2stuff.machines.grower.TileGrower.func_73660_a(TileGrower.scala:30)
	at net.minecraft.world.World.func_72939_s(World.java:1807)
```

Full crash report: https://gist.github.com/0blu/1a317f0ad4a45e6b31db06eeedd6ff38

**Comment by bdew** [comment]
That version is for alpha 8, it's not compatible with earlier versions of AE2.
For alpha 7 and lower use AE2Stuff 0.7.0.1
