### ISSUE TITLE
why crash?

### ISSUE THREAD

**Issue by fishbig2017** [bdew/ae2stuff#180]
---- Minecraft Crash Report ----
// Don't do that.

Time: 18-3-10 下午1:25
Description: Ticking block entity

java.lang.NoClassDefFoundError: appeng/core/WorldSettings
	at net.bdew.ae2stuff.grid.GridTile$$anonfun$1.apply$mcV$sp(GridTile.scala:37)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at net.bdew.lib.Event0.trigger(Event.scala:19)
	at net.bdew.lib.tile.TileExtended.func_145845_h(TileExtended.scala:63)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: appeng.core.WorldSettings
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 13 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.bdew.ae2stuff.grid.GridTile$$anonfun$1.apply$mcV$sp(GridTile.scala:37)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at net.bdew.lib.Event0.trigger(Event.scala:19)
	at net.bdew.lib.tile.TileExtended.func_145845_h(TileExtended.scala:63)

-- Block entity being ticked --
Details:
	Name: ae2stuff.Grower // net.bdew.ae2stuff.machines.grower.TileGrower
	Block type: ID #1647 (tile.ae2stuff.Grower // net.bdew.ae2stuff.machines.grower.BlockGrower$)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (1163,4,1123), Chunk: (at 11,0,3 in 72,70; contains blocks 1152,0,1120 to 1167,255,1135), Region: (2,2; contains chunks 64,64 to 95,95, blocks 1024,0,1024 to 1535,255,1535)
	Actual block type: ID #1647 (tile.ae2stuff.Grower // net.bdew.ae2stuff.machines.grower.BlockGrower$)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: 新的世界
	All players: 1 total; [EntityPlayerMP['fishbig'/217, l='新的世界', x=1163.91, y=5.63, z=1121.72]]
	Chunk stats: ServerChunkCache: 725 Drop: 0
	Level seed: 1805912561244091363
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (1284,4,1002), Chunk: (at 4,0,10 in 80,62; contains blocks 1280,0,992 to 1295,255,1007), Region: (2,1; contains chunks 64,32 to 95,63, blocks 1024,0,512 to 1535,255,1023)
	Level time: 264078 game time, 46916 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 8392 (now: true), thunder time: 148365 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3246329840 bytes (3095 MB) / 3802136576 bytes (3626 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAAAA	rftools{4.23} [RFTools] ([RFtools]rftools-4.23.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] ([热力膨胀]ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] ([热力膨胀]ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UCHIJAAAA	SolarFlux{1.7.10-0.8b} [Solar Flux] ([RF太阳能]SolarFlux-1.7.10-0.8b.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] ([R键整理]InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.10.9} [Storage Drawers] ([储物抽屉]StorageDrawers-1.7.10-1.10.9.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] ([应用能源2]appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] ([凿子]Chisel-2.9.5.11.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] ([更多使用设备]extrautilities-1.2.12.jar) 
	UCHIJAAAA	Botania{r1.8-249} [Botania] ([植物魔法]Botania+r1.8-249.jar) 
	UCHIJAAAA	Avaritia{1.13} [Avaritia] ([无尽贪婪]Avaritia-1.13.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.7.7} [Immersive Engineering] ([沉浸工程]ImmersiveEngineering-0.7.7.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build991} [Tinkers' Construct] ([匠魂]TConstruct-1.7.10-1.8.8.build991.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] ([大型反应堆]BigReactors-0.4.3A.jar) 
	UCHIJAAAA	ActuallyAdditions{1.7.10-r21} [Actually Additions] ([实用设备]ActuallyAdditions-1.7.10-r21.jar) 
	UCHIJAAAA	IC2{2.2.827-experimental} [IndustrialCraft 2] ([工业2]industrialcraft-2-2.2.827-experimental.jar) 
	UCHIJAAAA	journeymap{5.1.4p2} [JourneyMap] ([旅行者地图]journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJAAAA	wanionlib{1.7.10-1.8} [WanionLib] (WanionLib-1.7.10-1.8.jar) 
	UCHIJAAAA	avaritiaddons{1.4b} [Avaritiaddons] ([无尽贪婪拓展]Avaritiaddons-1.4b.jar) 
	UCHIJAAAA	universalsingularities{1.7.10-8.0} [Universal Singularities] ([无尽贪婪拓展]Universal+Singularities+[Version+8]-1.7.10.jar) 
	UCHIJAAAA	aobdsingularities{1.0.4} [Another One Bites The Dust: Singularities] (AOBDsingularities-1.0.4.jar) 
	UCHIJAAAA	eternalsingularity{1.7.10-.1.0.3} [Eternal Singularity] ([无尽贪婪拓展]EternalSingularity-1.7.10-1.0.4.jar) 
	UCHIJAAAA	SolarExpansion{1.6a} [Solar Expansion] ([普通太阳能]SolarExpansion-Basic-1.6a.jar) 
	UCHIJAAAA	bdlib{1.9.4.109} [BD Lib] ([晶体催生器前置]bdlib-1.9.4.109-mc1.7.10.jar) 
	UCHIJAAAA	ae2stuff{0.5.1.61} [AE2 Stuff] ([晶体催生器]ae2stuff-0.5.1.61-mc1.7.10.jar) 
	UCHIJAAAA	betterbuilderswands{0.8.1} [Better Builder's Wands] ([更好的建筑法杖]BetterBuildersWands-0.8.1-1.7.10r92+aec06c3.jar) 
	UCHIJAAAA	EnderTech{1.7.10-0.3.2.405} [EnderTech] ([末影水库]EnderTech-1.7.10-0.3.2.405.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] ([末影管道]EnderIO-1.7.10-2.3.0.429_beta.jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] ([潘马斯]Pam's+HarvestCraft+1.7.10Lb.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] ([热力膨胀]ThermalDynamics-[1.7.10]1.2.1-172.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] ([铁箱子]ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	ironbackpacks{1.7.10-1.2.20} [Iron Backpacks] ([铁背包]IronBackpacks-1.7.10-1.2.20.jar) 
	UCHIJAAAA	simplyjetpacks{1.5.3} [Simply Jetpacks] ([飞行背包]SimplyJetpacks-MC1.7.10-1.5.3.jar) 
	UCHIJAAAA	MouseTweaks{2.4.4} [Mouse Tweaks] ([鼠标手势]MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHIJAAAA	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
	UCHIJAAAA	DraconicEvolution{1.0.2h} [Draconic Evolution] ([龙之研究]Draconic-Evolution-1.7.10-1.0.2h.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	NEIAddons{1.12.13.38} [NEI Addons] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Developer{1.12.13.38} [NEI Addons: Developer Tools] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.13.38} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.13.38} [NEI Addons: Botany] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.13.38} [NEI Addons: Forestry] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.13.38} [NEI Addons: Crafting Tables] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.13.38} [NEI Addons: Ex Nihilo] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJAAAA	neieasyserach{0.8.7} [NEI Easy Serach] (neieasyserach-0.8.7.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAA	aobd{2.9.2} [Another One Bites The Dust] ([无尽贪婪]AOBD-2.9.2.jar) 
	UCHIJAAAA	UniDict{1.7.10-2.9.2} [UniDict] ([矿物词典]UniDict-1.7.10-2.9.2.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CoFHCore: -[1.7.10]3.1.4-329
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.2.1-172
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	List of loaded APIs: 
		* ActuallyAdditionsAPI (3) from [实用设备]ActuallyAdditions-1.7.10-r21.jar
		* appliedenergistics2|API (rv3) from [应用能源2]appliedenergistics2-rv3-beta-6.jar
		* Baubles|API (1.0.1.10) from [热力膨胀]ThermalFoundation-[1.7.10]1.2.6-118.jar
		* BotaniaAPI (61) from [无尽贪婪]Avaritia-1.13.jar
		* BuildCraftAPI|core (1.0) from [普通太阳能]SolarExpansion-Basic-1.6a.jar
		* BuildCraftAPI|tools (1.0) from [更多使用设备]extrautilities-1.2.12.jar
		* ChiselAPI (0.1.1) from [凿子]Chisel-2.9.5.11.jar
		* ChiselAPI|Carving (0.1.1) from [凿子]Chisel-2.9.5.11.jar
		* ChiselAPI|Rendering (0.1.1) from [凿子]Chisel-2.9.5.11.jar
		* CoFHAPI (1.7.10R1.0.3) from [普通太阳能]SolarExpansion-Basic-1.6a.jar
		* CoFHAPI|block (1.7.10R1.1.0) from [末影水库]EnderTech-1.7.10-0.3.2.405.jar
		* CoFHAPI|core (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|energy (1.7.10R1.0.3) from [普通太阳能]SolarExpansion-Basic-1.6a.jar
		* CoFHAPI|fluid (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHAPI|inventory (1.7.10R1.0.3) from [普通太阳能]SolarExpansion-Basic-1.6a.jar
		* CoFHAPI|item (1.7.10R1.1.0) from [末影水库]EnderTech-1.7.10-0.3.2.405.jar
		* CoFHAPI|items (1.7.10R1.0.3) from [普通太阳能]SolarExpansion-Basic-1.6a.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.3) from [普通太阳能]SolarExpansion-Basic-1.6a.jar
		* CoFHAPI|tileentity (1.7.10R1.0.3) from [普通太阳能]SolarExpansion-Basic-1.6a.jar
		* CoFHAPI|transport (1.7.10R1.0.3) from [普通太阳能]SolarExpansion-Basic-1.6a.jar
		* CoFHAPI|world (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib (1.7.10R1.0.4B1) from [末影水库]EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|audio (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui (1.7.10R1.0.4B1) from [末影水库]EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|gui|container (1.7.10R1.0.4B1) from [末影水库]EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|gui|element (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|gui|slot (1.7.10R1.0.4B1) from [末影水库]EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|inventory (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|render (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|render|particle (1.7.10R1.0.4B1) from [末影水库]EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|util (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|util|helpers (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* CoFHLib|util|position (1.7.10R1.0.4B1) from [末影水库]EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|world (1.7.10R1.0.4B1) from [末影水库]EnderTech-1.7.10-0.3.2.405.jar
		* CoFHLib|world|feature (1.7.10R1.2.1) from CoFHCore-[1.7.10]3.1.4-329.jar
		* DraconicEvolution|API (1.2) from [龙之研究]Draconic-Evolution-1.7.10-1.0.2h.jar
		* EnderIOAPI (0.0.2) from [末影管道]EnderIO-1.7.10-2.3.0.429_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from [末影管道]EnderIO-1.7.10-2.3.0.429_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from [末影管道]EnderIO-1.7.10-2.3.0.429_beta.jar
		* EnderIOAPI|Tools (0.0.2) from [末影管道]EnderIO-1.7.10-2.3.0.429_beta.jar
		* IC2API (1.0) from [工业2]industrialcraft-2-2.2.827-experimental.jar
		* ImmersiveEngineering|API (1.0) from [沉浸工程]ImmersiveEngineering-0.7.7.jar
		* McJtyLib (1.8.1) from mcjtylib-1.8.1.jar
		* RailcraftAPI|crafting (1.0.0) from [沉浸工程]ImmersiveEngineering-0.7.7.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from [储物抽屉]StorageDrawers-1.7.10-1.10.9.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from [储物抽屉]StorageDrawers-1.7.10-1.10.9.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from [储物抽屉]StorageDrawers-1.7.10-1.10.9.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from [储物抽屉]StorageDrawers-1.7.10-1.10.9.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from [储物抽屉]StorageDrawers-1.7.10-1.10.9.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from [储物抽屉]StorageDrawers-1.7.10-1.10.9.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from [储物抽屉]StorageDrawers-1.7.10-1.10.9.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from [储物抽屉]StorageDrawers-1.7.10-1.10.9.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from [储物抽屉]StorageDrawers-1.7.10-1.10.9.jar
		* Thaumcraft|API (4.2.2.0) from [潘马斯]Pam's+HarvestCraft+1.7.10Lb.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.0.2 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.3 from [普通太阳能]SolarExpansion-Basic-1.6a.jar).
                    It is a supported version, but that difference may lead to problems.
                  * Our API got loaded from [末影管道]EnderIO-1.7.10-2.3.0.429_beta.jar. That's unexpected.
                  * Our API got loaded from [末影管道]EnderIO-1.7.10-2.3.0.429_beta.jar. That's unexpected.
                  * Our API got loaded from [末影管道]EnderIO-1.7.10-2.3.0.429_beta.jar. That's unexpected.
                  * An unknown AE2 API is installed (rv3 from [应用能源2]appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                  * Our API got loaded from [末影管道]EnderIO-1.7.10-2.3.0.429_beta.jar. That's unexpected.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['fishbig'/217, l='新的世界', x=1163.91, y=5.63, z=1121.72]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by s1mples** [comment]
UCHIJAAAA	ae2stuff{0.5.1.61} [AE2 Stuff] ([晶体催生器]ae2stuff-0.5.1.61-mc1.7.10.jar)
UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] ([应用能源2]appliedenergistics2-rv3-beta-6.jar)

Use rv3 version of AE2 Stuff if you are using AE2 rv3 ....

https://minecraft.curseforge.com/projects/ae2-stuff/files/2270295
