### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by bsaksida** [bdew/ae2stuff#76]
I added to FTB Infinity 1.11.2. I use local server. I added EE3, ee3 helper, ae2ee3emcaddon, HelpFixer and ae2 stuff mods to it.

Placing growth chamber caused crash. I tried to place next on creative power cell (Thermal Expansion), on a ground with nothing around or next to Creative energy cell (AE2).

After servers restart, i can open chamber

I Cut the log up to point of crash and posted everything till end.

[18:36:03] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:642) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [M
inecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[li.class:?]
Caused by: java.lang.NoClassDefFoundError: appeng/core/worlddata/WorldData
        at net.bdew.ae2stuff.grid.Security$.getPlayerId(Security.scala:20) ~[Sec
urity$.class:?]
        at net.bdew.ae2stuff.grid.GridTile$$anonfun$1.apply$mcV$sp(GridTile.scal
a:36) ~[GridTile$$anonfun$1.class:?]
        at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19) ~[Event0
$$anonfun$trigger$1.class:?]
        at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19) ~[Event0
$$anonfun$trigger$1.class:?]
        at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-libra
ry-2.11.1.jar:?]
        at net.bdew.lib.Event0.trigger(Event.scala:19) ~[Event0.class:?]
        at net.bdew.lib.tile.TileExtended.func_145845_h(TileExtended.scala:63) ~
[TileExtended.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?
]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[
mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:636) ~[MinecraftServer.class:?]
        ... 4 more
Caused by: java.lang.ClassNotFoundException: appeng.core.worlddata.WorldData
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:191) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
        at net.bdew.ae2stuff.grid.Security$.getPlayerId(Security.scala:20) ~[Sec
urity$.class:?]
        at net.bdew.ae2stuff.grid.GridTile$$anonfun$1.apply$mcV$sp(GridTile.scal
a:36) ~[GridTile$$anonfun$1.class:?]
        at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19) ~[Event0
$$anonfun$trigger$1.class:?]
        at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19) ~[Event0
$$anonfun$trigger$1.class:?]
        at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-libra
ry-2.11.1.jar:?]
        at net.bdew.lib.Event0.trigger(Event.scala:19) ~[Event0.class:?]
        at net.bdew.lib.tile.TileExtended.func_145845_h(TileExtended.scala:63) ~
[TileExtended.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?
]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[
mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:636) ~[MinecraftServer.class:?]
        ... 4 more
Caused by: java.lang.NullPointerException
[18:36:03] [Server thread/ERROR]: This crash report has been saved to: f:\FTBInf
inity\.\crash-reports\crash-2015-10-04_18.36.03-server.txt
[18:36:03] [Server thread/INFO]: Stopping server
[18:36:03] [Server thread/INFO]: Saving players
[18:36:03] [Server thread/INFO]: Saving worlds
[18:36:03] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[18:36:03] [Server thread/INFO]: Saving chunks for level 'world'/Nether
[18:36:03] [Server thread/INFO]: Saving chunks for level 'world'/Dungeon
[18:36:03] [Server thread/INFO]: Saving chunks for level 'world'/The Last Millen
ium
[18:36:03] [Server thread/INFO] [mcjty.varia.Logging]: Cleaning up RFTools dimen
sions
[18:36:04] [Server thread/INFO] [FML]: Unloading dimension 0
[18:36:04] [Server thread/INFO] [FML]: Unloading dimension -1
[18:36:04] [Server thread/INFO] [FML]: Unloading dimension -34
[18:36:04] [Server thread/INFO] [FML]: Unloading dimension -112
[18:36:04] [Server thread/INFO] [FML]: Applying holder lookups
[18:36:04] [Server thread/WARN] [FML]: Unable to lookup chisel:cobblestoneWall f
or public static com.cricketcraft.chisel.block.BlockCarvableWall com.cricketcraf
t.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the re
gistry?
[18:36:04] [Server thread/WARN] [FML]: Unable to lookup chisel:obsidian2 for pub
lic static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.i
nit.ChiselBlocks.obsidian2. Is there something wrong with the registry?
[18:36:04] [Server thread/WARN] [FML]: Unable to lookup chisel:voidstonerunic fo
r public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chi
sel.init.ChiselBlocks.voidstonerunic. Is there something wrong with the registry
?
[18:36:04] [Server thread/WARN] [FML]: Unable to lookup chisel:circuits for publ
ic static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.in
it.ChiselBlocks.circuits. Is there something wrong with the registry?
[18:36:04] [Server thread/INFO] [FML]: Holder lookups applied
[18:36:04] [pool-4-thread-1/INFO] [EnderIO]: ServerChannelRegister: Dimensional
Transceiver data saved to f:\FTBInfinity\.\world\enderio\dimensionalTransceiver.
json
[18:36:04] [Server thread/INFO] [mcjty.varia.Logging]: RFTools: server is stoppi
ng. Shutting down gracefully
[18:36:04] [Server thread/INFO] [FML]: The state engine was in incorrect state S
ERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discar
ded.
Server process finished
Press any key to continue . . .

**Comment by bsaksida** [comment]
It seems it happens even to inscriber.

**Comment by bdew** [comment]
what versions of AE2 and AE2 stuff?

**Comment by bsaksida** [comment]
AE2stuff rv3-0.5.0.5
AE2 that comes with Infinity is rv2-stable-10.

Is by any chance AE2 stuff version incompatible with ae2?

**Comment by bdew** [comment]
> AE2stuff **rv3**-0.5.0.5
> AE2 that comes with Infinity is **rv2**-stable-10.

Yep, wrong version.

Grab the last stable release from [here](http://minecraft.curseforge.com/projects/ae2-stuff/files/2256440).
